"""empty message

Revision ID: 035bf3e43bd0
Revises: df2aca21dd46
Create Date: 2019-06-28 16:38:14.141998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '035bf3e43bd0'
down_revision = 'df2aca21dd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('mypic', sa.String(length=255), nullable=True))
    op.drop_column('article', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('pic', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('article', 'mypic')
    # ### end Alembic commands ###
