"""empty message

Revision ID: 0369240343ee
Revises: 035bf3e43bd0
Create Date: 2019-06-28 16:50:32.444226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0369240343ee'
down_revision = '035bf3e43bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('pic', sa.Integer(), nullable=True))
    op.drop_column('article', 'mypic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('mypic', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('article', 'pic')
    # ### end Alembic commands ###
