"""empty message

Revision ID: 24de135d3f54
Revises: 79f236819f8c
Create Date: 2019-06-22 15:00:09.749662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24de135d3f54'
down_revision = '79f236819f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'article', ['name'], unique=True)
    # ### end Alembic commands ###
