"""empty message

Revision ID: 44225a77c075
Revises: 24de135d3f54
Create Date: 2019-06-22 15:49:05.963603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44225a77c075'
down_revision = '24de135d3f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
