"""empty message

Revision ID: 7093b63e03b7
Revises: 9c71758d62fd
Create Date: 2019-06-23 15:07:27.322225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7093b63e03b7'
down_revision = '9c71758d62fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sort', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sort', 'num')
    # ### end Alembic commands ###
