"""empty message

Revision ID: df2aca21dd46
Revises: 7093b63e03b7
Create Date: 2019-06-28 16:30:14.760579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2aca21dd46'
down_revision = '7093b63e03b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('pic', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'pic')
    # ### end Alembic commands ###
